### ISSUE TITLE
Add config section for user defined tags to add to all metrics

### ISSUE THREAD

**Issue by NicolasBissig** [NicolasBissig/ServerMetrics#2]
Like this;

```yml
enabled: true

tags:
  key: "value"
  server: "Server name"
```
