### ISSUE TITLE
DiskSpaceMetrics should use WorldContainer and all drives

### ISSUE THREAD

**Issue by NicolasBissig** [NicolasBissig/ServerMetrics#5]
Maybe expand config here like this:

```yml
    DiskSpace:
      enabled: true
      world-container: true
      per-drive: true
```
